### ISSUE TITLE
Failed loading plugin

### ISSUE THREAD

**Issue by daniel4099** [lucavb/homebridge-magic-blue-bulb#7]
Hi

I'm not able to run after install

ERROR LOADING PLUGIN homebridge-magic-blue-bulb:
[2018-10-23 13:47:06] Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-magic-blue-bulb/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[2018-10-23 13:47:06] ====================

**Comment by lucavb** [comment]
Did you run homebridge as root/sudo? Unless you've added the user to the bluetooth group (if that even works) homebridge is going to need that.

**Comment by lucavb** [comment]
Close due to inactivity
